### ISSUE TITLE
TBrowser seg faults when jet variables in EventTree are accessed

### ISSUE THREAD

**Issue by pjdunne** [ajgilbert/ICHiggsTauTau#70]
Both Adinda and I have noticed this behaviour in CMSSW_7_4_5, it only seems to affect the jet collections. Accessing them with TTree::Draw works fine though.

**Comment by ajgilbert** [comment]
even when the dictionary is loaded first?

**Comment by pjdunne** [comment]
So this is another thing we've both been seeing, when you open root you get:

Warning in <TInterpreter::ReadRootmapFile>: class  pair<std::string,double> found in libDataFormatsStdDictionaries.so  is already in libUserCodeICHiggsTauTau.so 
Warning in <TInterpreter::ReadRootmapFile>: class  pair<string,double> found in libDataFormatsStdDictionaries.so  is already in libUserCodeICHiggsTauTau.so 
Warning in <TInterpreter::ReadRootmapFile>: class  edm::Wrapper<std::vector<unsigned long> > found in libDataFormatsWrappedStdDictionaries.so  is already in libUserCodeICHiggsTauTau.so 
Warning in <TInterpreter::ReadRootmapFile>: class  edm::Wrapper<vector<unsigned long> > found in libDataFormatsWrappedStdDictionaries.so  is already in libUserCodeICHiggsTauTau.so

So I presume it is loading the dictionary, but something is going wrong.

**Comment by adewit** [comment]
Ok, probably not a problem on our side, rather a root 6 problem, see https://sft.its.cern.ch/jira/browse/ROOT-6748 for something similar
We're on root 6.02/05 with CMSSW 7_4_5, problem should be fixed in root 6.04 (don't know which CMSSW version that will correspond to)

**Comment by ajgilbert** [comment]
yes I expect it's just some root6 problem - though having said that it's not obvious these warning messages are related to the segfault. let's leave this issue open for now until it's either understood or fixed in a future root version

**Comment by ajgilbert** [comment]
looked into this - problem still happens with 6.02/10 which is in 7_5_0. The warnings can be suppressed by removing the conflicting definition in classes_def.xml, but this doesn't affect the segfault. As far as I can tell it's caused when root tries to figure out what class methods of the jet class are available that it can be in the tbrowser panel. A temporary solution will be to suppress this automatic loading of the dictionaries that seems to be the norm now in root6, but I didn't figure out a nice way to do this yet. Ideally we should also create a minimal example that can cause a crash and raise a ticket with the root developers.

**Comment by adewit** [comment]
This problem is fixed in root 6.06/01 ( = CMSSW 8, it'll be a while until we're on a release that we'll actually 'benefit' from the fix with). I've also removed the warning-causing conflicting definitions in classes_def.xml -  I think we can close this.
